name: Continuous Integration

on: [push, pull_request]

jobs:
  macos:
    name: macOS
    runs-on: macOS-latest
    strategy:
      matrix:
        xcode:
          - "11.3"
        action:
          - build
          - test
    steps:
    - uses: actions/checkout@v1
    - name: Xcode version
      run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
    - name: Action
      run: make ${{ matrix.action }}
